USE Employee;

--ALL STRING FUNCTIONS
--UPPER
SELECT UPPER(emp_name) FROM employee_info;

--LOWER
SELECT LOWER(emp_name) FROM employee_info;

--CONCAT
SELECT CONCAT(emp_name,emp_age) FROM employee_info;

--LEN
SELECT LEN(emp_name) FROM employee_info;

--REPLACE
SELECT REPLACE('SWARANJALI HARKARE','HARKARE','GAVADE') ;

--SUBSTRING
SELECT SUBSTRING('SWARANJALI HARKARE',1,10)

--LEFT
SELECT LEFT('SWARANJALI HARKARE',5)

--RIGHT
SELECT RIGHT('SWARANJALI HARKARE',5)

--TRIM
SELECT TRIM('      SWARANJALI HARKARE')

--RTRIM
SELECT RTRIM('      SWARANJALI HARKARE     ')

--LTRIM
SELECT LTRIM('      SWARANJALI HARKARE     ')

--REVERSE
SELECT REVERSE('SWARANJALI HARKARE')
